import { Box, Flex, Image, Text } from "@chakra-ui/react";

export function ContinentsSlides() {

  return (
    <Flex
      w="100%"
      maxWidth={1240}
      h={450}
      m="0 auto"
      position="relative"
      mt={20}
      mb={10}
    >
      <Image
        src="/ContinentImage.png"
        alt="Europa"
        position="absolute"
        w="100%"
        h="100%"
      />
      <Image
        src="/Previous.svg"
        alt="Anterior"
        zIndex="5"
        w="60px"
        h="60px"
        position="absolute"
        top="195px"
        left="15px"
        cursor="pointer"
      />
      <Flex
        position="absolute"
        w={324}
        h={116}
        top="167px"
        left="36.9%"
        flexDirection="column"
        justifyContent="space-between"
        alignItems="center"
      >
        <Text
          fontWeight={700}
          fontSize="5xl"
          lineHeight="72px"
          color="#F5F8FA"
        >
          Europa
        </Text>
        <Text
          fontWeight={700}
          fontSize="2xl"
          lineHeight="72px"
          color="#DADADA"
        >
          O continente mais antigo
        </Text>
      </Flex>
      <Image
        src="/Next.svg"
        alt="Anterior"
        zIndex="5"
        w="60px"
        h="60px"
        position="absolute"
        top="195px"
        right="15px"
        cursor="pointer"
      />
      <Flex
        position="absolute"
        w={128}
        h="16px"
        top="90%"
        left="44.8%"
        justifyContent="space-between"
        alignItems="center"
      >
        <Box
          bg="#FFBA08"
          w="16px"
          h="16px"
          borderRadius="50%"
        />
        <Box
          bg="#999999"
          w="16px"
          h="16px"
          borderRadius="50%"
        />
        <Box
          bg="#999999"
          w="16px"
          h="16px"
          borderRadius="50%"
        />
        <Box
          bg="#999999"
          w="16px"
          h="16px"
          borderRadius="50%"
        />
        <Box
          bg="#999999"
          w="16px"
          h="16px"
          borderRadius="50%"
        />
      </Flex>
    </Flex>
  )
}